import './global.css';

export const metadata = {
  title: 'Welcome to music',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav>
          <ul className="flex justify-center">
            <li className="p-2 m-2 border-2">Add Artist</li>
            <li className="p-2 m-2 border-2">Add Album</li>
            <li className="p-2 m-2 border-2">Add Song</li>
            <li className="p-2 m-2 border-2">View Artists</li>
            <li className="p-2 m-2 border-2">View Albums</li>
            <li className="p-2 m-2 border-2">View Songs</li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
